administrator:  # 可不填,默认当前微信号
  name:
  wxid:
plugins:
  info:
    gemini:
      access:
        - wxid_xxxx
        - wxid_xxxx
        - wxid_xxxx
      enable: true
      token:  # gemini的token,没有token请不要开启gemini
    gpt:
      access:
        - wxid_xxxx
        - wxid_xxxx
        - wxid_xxxx
      enable: true
    hitokoto:
      access:
        - wxid_xxxx
        - wxid_xxxx
        - wxid_xxxx
      enable: true
    menu:
      access:
        - wxid_xxxx
        - wxid_xxxx
        - wxid_xxxx
      enable: true
  list:  # 请将插件放在plugins目录下
    - AI
    - funcs
    - Administrator
